name: scanning_effect
description: Scanning effect for wrapping around a camera view

version: 1.0.1
homepage:  https://github.com/chihuy105/scanning_effect
#publish_to: https://github.com/chihuy105/scanning_effect

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: